#!/bin/bash
set -eo pipefail
function run_cmd {
  exec $*
}

function main {
  local cmd="$@"
  [ -z "$cmd" ] &&\
    cmd="tinyproxy -d -c /tinyproxy/$CONFIG"

  [ -f "/tinyproxy/$CONFIG" ] ||\
    envtpl -o "/tinyproxy/$CONFIG" /tinyproxy.conf.tpl
  [ -d /var/run/tinyproxy ] || mkdir -p /var/run/tinyproxy
  run_cmd "$cmd"
}

ulimit -n 32768
main "$@"
exit 0